path:
  root: /disk/data1/aaldana/avsec4/avsec4_data/
  metadata_dir: ${path.root}/metadata/


random_seed: 0
shuffle_rooms: False

# Build rooms
room_datasets:
  train:
    rpf_location: ${path.root}/train/rooms/rpf
    n_interferers: 3
    n_rooms: 6000
    start_room: 1
  dev:
    rpf_location: ${path.root}/dev/rooms/rpf
    n_interferers: 3
    n_rooms: 2500
    start_room: 6001

# Instantiate_scenes
scene_datasets:
  train:
    n_scenes: 34525
    room_selection: SEQUENTIAL
    scene_start_index: 1
  dev:
    n_scenes: 3365
    room_selection: SEQUENTIAL
    scene_start_index: 34526

target:
  target_speakers: ${path.metadata_dir}/target_speech_list.json
  target_selection: SEQUENTIAL
  pre_samples_range: [0, 0]
  post_samples_range: [0, 0]

snr_range:
  train: [-10, 10]
  dev: [-10, 10]

interferer:
  speech_interferers: ${path.metadata_dir}/masker_speech_list.json
  noise_interferers: ${path.metadata_dir}/masker_nonspeech_list.json
  music_interferers: ${path.metadata_dir}/masker_music_list.json
  number: [1, 2, 3]
  start_time_range: [0, 0]
  end_early_time_range: [0, 0]

listener:
  heads: ["BuK", "DADEC", "KEMAR", "VP_E1", "VP_E2", "VP_E4", "VP_E5", "VP_E6", "VP_E7", "VP_E8", "VP_E9", "VP_E11", "VP_E12", "VP_E13", "VP_N1", "VP_N3", "VP_N4", "VP_N5", "VP_N6"]
  channels: ["ED"]
  #head rotation parameters are not used in AVSEC
  # parameters all in units of samples or degrees
  # The time at which the head turn starts relative to target speaker onset
  relative_start_time_range: [0, 0] #[-28004, 38147]  # -0.635 s to 0.865 s
  # Rotations have a normally distributed duration
  duration_mean: 0 #8820
  duration_sd: 0 #441  # 100 ms
  # Head is initially pointing away from talker, uniform within a range
  # Note it can be either offset to left or right - drawn at random
  angle_initial_mean: 0 #25
  angle_initial_sd: 0 #5
  # Head turns to point at the speaker within some margin
  angle_final_range: [0, 10]

# Render scenes
render_starting_chunk: 0  # there are (6000 train + 2500 dev) / (12 + 5) = 500 trunks in total. If multi_run, should be 0, 10, 20, 30, ..., 490 if render_n_chunk_to_process=10
render_n_chunk_to_process: 500 #50  # i.e. (12 train + 5 dev) * 10 scenes to render. If not multi_run, set 50

scene_renderer:
  train:
    paths:
      hoairs: ${path.root}/train/rooms/HOA_IRs_16k
      hrirs: ${path.root}/hrir/HRIRs_MAT
      scenes: ${path.root}/train/scenes
      targets: ${path.root}/train/targets
      videos: ${path.root}/train/targets_video
      interferers: ${path.root}/train/interferers/{type}
    metadata:
      room_definitions: ${path.metadata_dir}/rooms.train.json
      scene_definitions: ${path.metadata_dir}/scenes.train.json
      hrir_metadata: ${path.metadata_dir}/hrir_data.json
    chunk_size: 70 #12
  dev:
    paths:
      hoairs: ${path.root}/dev/rooms/HOA_IRs_16k
      hrirs: ${path.root}/hrir/HRIRs_MAT
      scenes: ${path.root}/dev/scenes
      targets: ${path.root}/dev/targets
      videos: ${path.root}/dev/targets_video
      interferers: ${path.root}/dev/interferers/{type}
    metadata:
      room_definitions: ${path.metadata_dir}/rooms.dev.json
      scene_definitions: ${path.metadata_dir}/scenes.dev.json
      hrir_metadata: ${path.metadata_dir}/hrir_data.json
    chunk_size: 7 #5


render_params:
  ambisonic_order: 6
  equalise_loudness: False
  reference_channel: 0
  channel_norms: [6.0] #not used in AVSEC
  binaural_render: True
  monoaural_render: True
hydra:
  run:
    dir: .
  job:
    chdir: True

defaults:
  - override hydra/launcher: cec2_submitit_local
